---
title: "data manipulation"
output: html_document
---

I'm an R Markdown document! 


```{r}
library(tidyverse)
```

## load in FAS litters data
```{r}
lit_df <- read_csv('./data_import_examples/FAS_litters.csv')
lit_df <- df <- janitor::clean_names(lit_df)
```

## select

```{r}
select(lit_df,group,gd0_weight)
```
```{r}
select(lit_df,group,gd0_weight:gd_of_birth)
```
```{r}
select(lit_df,-gd0_weight)
```

rename columns:
```{r}
select(lit_df,GROUP=group,LITTER=litter_number)
rename(lit_df,GROUP=group,LITTER=litter_number)
```
```{r}
select(lit_df,starts_with('gd'))
```
```{r}
select(lit_df,litter_number, everything())
```
```{r}
relocate(lit_df,gd0_weight)
```
```{r}
filter(lit_df,gd0_weight<22)
```

```{r}
filter(lit_df,gd_of_birth!=20)
```
```{r}
filter(lit_df,gd0_weight<22,gd_of_birth==20)
```
```{r}
filter(lit_df,group=='Mod8')
```
```{r}
filter(lit_df,group%in%c('Mod8','Con7'))
```

## mutate

```{r}
mutate(lit_df,wt_gain=as.numeric(gd18_weight)-as.numeric(gd0_weight),group = str_to_lower(group))
```













