---
title: "data from web"
output: html_document
---

```{r}
library(tidyverse)
library(rvest)
library(httr)
```
```{r}
knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = '90%'
)

theme_set(theme_minimal()+theme(legend.position = 'bottom'))

options(
  ggplot2.continuous.color = 'viridis',
  ggplot2.continuous.fill = 'viridis'
)

scale_color_discrete = scale_color_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```

```{r}
url = "http://samhda.s3-us-gov-west-1.amazonaws.com/s3fs-public/field-uploads/2k15StateFiles/NSDUHsaeShortTermCHG2015.htm"
drug_use_html = read_html(url)

drug_use_html
```

get pieces I actually need

```{r}
marj_use_df = 
  drug_use_html|>
  html_table()|>
  first()|>
  slice(-1)
```

```{r}
nyc_cost <- read_html('https://www.bestplaces.net/cost_of_living/city/new_york/new_york')|>
  html_table()|>
  first()
```

```{r}
swm_html = 
  read_html("https://www.imdb.com/list/ls070150896/")
```

```{r}
swm_title_vector = 
  swm_html|>
  html_elements('.ipc-title-link-wrapper .ipc-title__text')|>
  html_text()
```

```{r}
swm_time_vector = 
swm_html|>
  html_elements('.dli-title-metadata-item:nth-child(2)')|>
  html_text()
```

```{r}
read_html <- 
  read_html('https://books.toscrape.com/')
```

```{r}
swm_score_vec = 
  swm_html |>
  html_elements(".metacritic-score-box") |>
  html_text()
```

```{r}
swm_df = 
  tibble(
    title = swm_title_vector,
    score = swm_score_vec,
    runtime = swm_time_vector)
```


using API

```{r water data}
nyc_water <- 
  GET('https://data.cityofnewyork.us/resource/ia2d-e54m.csv')|>
  content("parsed")
```

```{r json file}
nyc_water = 
  GET("https://data.cityofnewyork.us/resource/ia2d-e54m.json") |> 
  content("text") |>
  jsonlite::fromJSON() |>
  as_tibble()
```

```{r}
brfss_smart2010 = 
  GET("https://chronicdata.cdc.gov/resource/acme-vg9e.csv",
      query = list("$limit" = 5000)) |> 
  content("parsed")
```




