---
title: "strings and factors"
output: html_document
---

```{r}
library(rvest)
library(p8105.datasets)
library(stringr)
library(forcats)
library(tidyverse)
library(ggplot2)
library(viridis)
```

```{r}
string_vec = c('my','name','is','jmm')

str_detect(string_vec,'jmm')
str_replace(string_vec, 'e', 'E')
```

```{r}
string_vec = c(
  "i think we all rule for participating",
  "i think i have been caught",
  "i think this will be quite fun actually",
  "it will be fun, i think"
  )

str_detect(string_vec, "^i think") #begin with
str_detect(string_vec, "i think")
str_detect(string_vec, "i think$") #end with
```

```{r}
string_vec = c(
  "Time for a Pumpkin Spice Latte!",
  "went to the #pumpkinpatch last weekend",
  "Pumpkin Pie is obviously the best pie",
  "SMASHING PUMPKINS -- LIVE IN CONCERT!!"
  )

str_detect(string_vec,"[Pp]umpkin")
str_detect(string_vec,"pumpkin")
str_detect(string_vec,"Pumpkin")
str_detect(string_vec,"PUMPKIN")
```

```{r}
string_vec = c(
  '7th inning stretch',
  '1st half soon to begin. Texas won the toss.',
  'she is 5 feet 4 inches tall',
  '3AM - cant sleep :('
  )

str_detect(string_vec, "[0-4]")
str_detect(string_vec, "[0-9][a-z]")
str_detect(string_vec, "^[0-9][a-zA-Z]")
```

```{r}
string_vec = c(
  'Its 7:11 in the evening',
  'want to go to 7-11?',
  'my flight is AA711',
  'NetBios: scanning ip 203.167.114.66'
  )

str_detect(string_vec, "7.11") #"." matches everything
```

```{r}
string_vec = c(
  'The CI is [2, 5]',
  ':-]',
  ':-[',
  'I found the answer on pages [6-7]'
  )
##str_detect(string_vec, "[")
str_detect(string_vec, "\\[")
```

```{r}
vec_sex = factor(c("male", "male", "female", "female"))
vec_sex
as.numeric(vec_sex)
```

```{r}
vec_sex = fct_relevel(vec_sex, "male")
vec_sex
```
NSDUH

```{r}
nsduh_url = "http://samhda.s3-us-gov-west-1.amazonaws.com/s3fs-public/field-uploads/2k15StateFiles/NSDUHsaeShortTermCHG2015.htm"

table_marj = 
  read_html(nsduh_url) |> 
  html_table() |> 
  first() |>
  slice(-1) #select or remove rows
```

```{r}
data_marj = 
  table_marj |>
  select(-contains("P Value")) |>
  pivot_longer(
    -State,
    names_to = "age_year", 
    values_to = "percent") |>
  separate(age_year, into = c("age", "year"), sep = "\\(") |>
  mutate(
    year = str_replace(year, "\\)", ""),
    percent = str_replace(percent, "[a-c]$", ""),
    percent = as.numeric(percent))
```

```{r}
knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = '90%'
)

theme_set(theme_minimal()+theme(legend.position = 'bottom'))

options(
  ggplot2.continuous.color = 'viridis',
  ggplot2.continuous.fill = 'viridis'
)

scale_color_discrete = scale_color_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```

```{r}
data_marj|>
  filter(age =='12-17')|>
  mutate(State = fct_reorder(State, percent))|>
  ggplot(aes(x = State, y = percent, color = year))+
  geom_point()+
  theme(axis.text.x = element_text(angle = 90, hjust = 1))
```

NYC restaurant Inspections

```{r}
data("rest_inspec")

rest_inspec |> 
  group_by(boro, grade) |> 
  summarize(n = n()) |> # count(boro, grade)
  pivot_wider(names_from = grade, values_from = n)
```

```{r}
rest_inspec = 
  rest_inspec|>
  filter(
    str_detect(grade, '[A-C]'),
    !(boro == 'Missing')
  )
```

```{r}
rest_inspec |> 
  filter(str_detect(dba, "Pizza"))|>
  mutate(#boro = fct_relevel(boro, 'STATEN ISLAND')
    boro = fct_infreq(boro),
    #boro = str_replace(boro,'MANHATTAN','THE CITY')
    )|>
  ggplot(aes(x = boro))+
  geom_bar()
```

one last thing about factors

```{r}
rest_inspec|>
  filter(str_detect(dba, "Pizza"))|>
  lm(zipcode ~ boro, data = _)
```
```{r}
rest_inspec|>
  filter(str_detect(dba, "Pizza"))|>
  mutate(#boro = fct_relevel(boro, 'STATEN ISLAND')
    boro = fct_infreq(boro),
    #boro = str_replace(boro,'MANHATTAN','THE CITY')
    )|>
  lm(zipcode ~ boro, data = _)
```






