---
title: "data tidy"
output: html_document
---

I'm an R Markdown document! 


```{r}
library(tidyverse)
library(readxl)
```

## pivot_longer
```{r}
pulse_df = 
  haven::read_sas("./data_import_examples/public_pulse_data.sas7bdat") |>
  janitor::clean_names()
```

```{r}
pulse_tidy_df = 
  pivot_longer(
    pulse_df, 
    bdi_score_bl:bdi_score_12m,
    names_to = "visit", 
    values_to = "bdi",
    names_prefix = 'bdi_score_')|>
  mutate(visit = replace(visit, visit=='bl','00m'),
         visit = factor(visit))|>
  relocate(id,visit)

```

```{r}
lit_df <- read_csv('./data_import_examples/FAS_litters.csv')|>
  janitor::clean_names()|>
  pivot_longer(cols = gd0_weight:gd18_weight,
               names_to = 'gd_time',
               values_to = 'weight')|>
  mutate(
    gd_time = case_match(
      gd_time,
      'gd0_weight'~0,
      'gd18_weight'~18
    )
  )
```


## pivot_wider

```{r}
analysis_df = 
  tibble(
    group = c("treatment", "treatment", "control", "control"),
    time = c("pre", "post", "pre", "post"),
    mean = c(4,10, 4.2, 5))|>
      pivot_wider(
        names_from = 'time',
        values_from = 'mean'
      )
```

## bind tables
```{r}
fellowship_ring <- 
  read_excel('./data_import_examples/LotR_Words.xlsx',range = 'B3:D6')|>
  mutate(movie = 'felloeship_ring')
two_towers <- 
  read_excel('./data_import_examples/LotR_Words.xlsx',range = 'F3:H6')|>
  mutate(movie = 'two_towers')
return_king <- 
  read_excel('./data_import_examples/LotR_Words.xlsx',range = 'J3:L6')|>
  mutate(movie = 'return_king')
```

```{r}
lotr_df <- 
  bind_rows(fellowship_ring, two_towers, return_king) |>
  janitor::clean_names() |>
  pivot_longer(
    female:male,
    names_to = "gender", 
    values_to = "words") |>
  mutate(race = str_to_lower(race)) |> 
  select(movie, everything()) 

```

## join DAF datatsets

```{r}
lit_df <- 
  read_csv('./data_import_examples/FAS_litters.csv',na = c('NA','','.'))|>
  janitor::clean_names()|>
  mutate(
    wt_gain = gd18_weight-gd0_weight
  )|>
  separate(
    group,into = c('dose','day_of_treatment'),sep = 3
  )

```

```{r}
pup_df = 
  read_csv(
    "./data_import_examples/FAS_pups.csv",
    na = c("NA", "", ".")) |>
  janitor::clean_names() |>
  mutate(
    sex = 
      case_match(
        sex, 
        1 ~ "male", 
        2 ~ "female"),
    sex = as.factor(sex)) 
```

join datasets:

```{r}
fas_df <- 
  left_join(pup_df,lit_df,by = 'litter_number') 
```






